#!/bin/bash

#
# history options 
#
HISTFILE=~/.bash_history
export HISTSIZE=1000
export HISTFILESIZE=50000
export HISTCONTROL=ignoreboth
export HISTTIMEFORMAT='%Y-%m-%d %H:%M '
export PROMPT_COMMAND='history -a; history -r'
export HISTIGNORE='history:pwd:ls:ls *:ll'
alias history='history'
alias h='history'

#
# system
#
