#!/bin/bash
if [ -e ~/.bash/git-prompt.sh ];then
    source ~/.bash/git-prompt.sh
fi
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWUPSTREAM=1
GIT_PS1_SHOWSTASHSTATE=1
export PS1='\[\e[36m\]\u \[\e[0m\]\W$(__git_ps1) \$ '

#
# completion
#
if [ -e ~/.bash/git-completion.bash ];then
    source ~/.bash/git-completion.bash
fi