#!/bin/zsh
autoload -Uz vcs_info
setopt prompt_subst
zstyle ':vcs_info:*' branchformat '%b:r%r'
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr "%F{white}"
zstyle ':vcs_info:git:*' unstagedstr "%F{white}"
zstyle ':vcs_info:*' formats "%c%u(%b)"
zstyle ':vcs_info:*' actionformats '[%b|%a]'
precmd () { vcs_info }
PROMPT='%F{cyan}%n%f %c$vcs_info_msg_0_ \$ '

#
# completion
#
autoload -Uz compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin \
        /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin
zstyle ':completion:*' list-colors "${LS_COLORS}"
setopt complete_in_word
zstyle ':completion:*:default' menu select=1
zstyle ':completion::complete:*' use-cache true
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
setopt list_packed